In [8]:
!pip install pandas==2.1.0 boto3==1.28.0 python-dotenv==1.0.0 duckdb==0.10.0 pyarrow==14.0.1 slack-sdk==3.27.1

Collecting pandas==2.1.0
  Using cached pandas-2.1.0-cp311-cp311-win_amd64.whl.metadata (18 kB)
Requirement already satisfied: boto3==1.28.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (1.28.0)
Requirement already satisfied: python-dotenv==1.0.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (1.0.0)
Collecting duckdb==0.10.0
  Using cached duckdb-0.10.0-cp311-cp311-win_amd64.whl.metadata (782 bytes)
Collecting pyarrow==14.0.1
  Using cached pyarrow-14.0.1-cp311-cp311-win_amd64.whl.metadata (3.1 kB)
Requirement already satisfied: slack-sdk==3.27.1 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (3.27.1)
Requirement already satisfied: numpy>=1.23.2 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from pandas==2.1.0) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from pandas==2.1.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from pandas==2.1.0) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from pandas==2.1.0) (2025.3)
Requirement already satisfied: botocore<1.32.0,>=1.31.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from boto3==1.28.0) (1.31.85)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from boto3==1.28.0) (1.1.0)
Requirement already satisfied: s3transfer<0.7.0,>=0.6.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from boto3==1.28.0) (0.6.2)
Requirement already satisfied: urllib3<2.1,>=1.25.4 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0) (2.0.7)
Requirement already satisfied: six>=1.5 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from python-dateutil>=2.8.2->pandas==2.1.0) (1.17.0)
Using cached pandas-2.1.0-cp311-cp311-win_amd64.whl (11.0 MB)
Using cached duckdb-0.10.0-cp311-cp311-win_amd64.whl (9.6 MB)
Using cached pyarrow-14.0.1-cp311-cp311-win_amd64.whl (24.6 MB)
Installing collected packages: pyarrow, duckdb, pandas

  Attempting uninstall: pyarrow

    Found existing installation: pyarrow 23.0.1

   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
    Uninstalling pyarrow-23.0.1:
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
      Successfully uninstalled pyarrow-23.0.1
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
   ---------------------------------------- 0/3 [pyarrow]
  Attempting uninstall: duckdb
   ---------------------------------------- 0/3 [pyarrow]
   ------------- -------------------------- 1/3 [duckdb]
    Found existing installation: duckdb 1.5.1
   ------------- -------------------------- 1/3 [duckdb]
    Uninstalling duckdb-1.5.1:
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
      Successfully uninstalled duckdb-1.5.1
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
   ------------- -------------------------- 1/3 [duckdb]
  Attempting uninstall: pandas
   ------------- -------------------------- 1/3 [duckdb]
    Found existing installation: pandas 3.0.1
   ------------- -------------------------- 1/3 [duckdb]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
    Uninstalling pandas-3.0.1:
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
      Successfully uninstalled pandas-3.0.1
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Hi\.conda\envs\moh_S\Lib\site-packages\~yarrow.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Hi\.conda\envs\moh_S\Lib\site-packages\~-arrow'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Hi\AppData\Local\Temp\pip-uninstall-blpg75g3'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Hi\.conda\envs\moh_S\Lib\site-packages\~.ndas'.
  You can safely remove it manually.

In [9]:
!pip install apache-airflow==2.8.1 --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.8.1/constraints-3.11.txt"

Requirement already satisfied: apache-airflow==2.8.1 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (2.8.1)
Requirement already satisfied: alembic<2.0,>=1.6.3 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (1.13.1)
Requirement already satisfied: argcomplete>=1.10 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (3.2.1)
Requirement already satisfied: asgiref in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (3.7.2)
Requirement already satisfied: attrs>=22.1.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (23.2.0)
Requirement already satisfied: blinker in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (1.7.0)
Requirement already satisfied: colorlog<5.0,>=4.0.2 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (4.8.0)
Requirement already satisfied: configupdater>=3.1.1 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (3.2)
Requirement already satisfied: connexion<3.0,>=2.10.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from connexion[flask]<3.0,>=2.10.0->apache-airflow==2.8.1) (2.14.2)
Requirement already satisfied: cron-descriptor>=1.2.24 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (1.4.0)
Requirement already satisfied: croniter>=0.3.17 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (2.0.1)
Requirement already satisfied: cryptography>=0.9.3 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (41.0.7)
Requirement already satisfied: deprecated>=1.2.13 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (1.2.14)
Requirement already satisfied: dill>=0.2.2 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (0.3.1.1)
Requirement already satisfied: flask-appbuilder==4.3.10 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (4.3.10)
Requirement already satisfied: flask-caching>=1.5.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (2.1.0)
Requirement already satisfied: flask-login>=0.6.2 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (0.6.3)
Requirement already satisfied: flask-session>=0.4.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (0.5.0)
Requirement already satisfied: flask-wtf>=0.15 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (1.2.1)
Requirement already satisfied: flask<2.3,>=2.2 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (2.2.5)
Requirement already satisfied: fsspec>=2023.10.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (2023.12.2)
Requirement already satisfied: google-re2>=1.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (1.1)
Requirement already satisfied: gunicorn>=20.1.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (21.2.0)
Requirement already satisfied: httpx in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (0.23.3)
Requirement already satisfied: itsdangerous>=2.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (2.1.2)
Requirement already satisfied: jinja2>=3.0.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (3.1.3)
Requirement already satisfied: jsonschema>=4.18.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (4.20.0)
Requirement already satisfied: lazy-object-proxy in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (1.10.0)
Requirement already satisfied: linkify-it-py>=2.0.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (2.0.2)
Requirement already satisfied: lockfile>=0.12.2 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (0.12.2)
Requirement already satisfied: markdown-it-py>=2.1.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (3.0.0)
Requirement already satisfied: markdown>=3.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (3.5.2)
Requirement already satisfied: markupsafe>=1.1.1 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (2.1.3)
Requirement already satisfied: marshmallow-oneofschema>=2.0.1 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (3.0.1)
Requirement already satisfied: mdit-py-plugins>=0.3.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (0.4.0)
Requirement already satisfied: opentelemetry-api>=1.15.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (1.22.0)
Requirement already satisfied: opentelemetry-exporter-otlp in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (1.22.0)
Requirement already satisfied: packaging>=14.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (23.2)
Requirement already satisfied: pathspec>=0.9.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (0.12.1)
Requirement already satisfied: pendulum<4.0,>=2.1.2 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (3.0.0)
Requirement already satisfied: pluggy>=1.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (1.3.0)
Requirement already satisfied: psutil>=4.2.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (5.9.7)
Requirement already satisfied: pydantic>=2.3.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (2.5.3)
Requirement already satisfied: pygments>=2.0.1 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (2.17.2)
Requirement already satisfied: pyjwt>=2.0.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (2.8.0)
Requirement already satisfied: python-daemon>=3.0.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (3.0.1)
Collecting python-dateutil>=2.3 (from apache-airflow==2.8.1)
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: python-nvd3>=0.15.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (0.15.0)
Requirement already satisfied: python-slugify>=5.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (8.0.1)
Requirement already satisfied: rfc3339-validator>=0.1.4 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (0.1.4)
Requirement already satisfied: rich-argparse>=1.0.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (1.4.0)
Requirement already satisfied: rich>=12.4.4 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (13.7.0)
Requirement already satisfied: setproctitle>=1.1.8 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (1.3.3)
Requirement already satisfied: sqlalchemy-jsonfield>=1.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (1.0.2)
Requirement already satisfied: sqlalchemy<2.0,>=1.4.28 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (1.4.51)
Requirement already satisfied: tabulate>=0.7.5 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (0.9.0)
Requirement already satisfied: tenacity!=8.2.0,>=6.2.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (8.2.3)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (2.4.0)
Requirement already satisfied: unicodecsv>=0.14.1 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (0.14.1)
Requirement already satisfied: universal-pathlib>=0.1.4 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (0.1.4)
Requirement already satisfied: werkzeug<3,>=2.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (2.2.3)
Requirement already satisfied: apache-airflow-providers-common-io in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (1.2.0)
Requirement already satisfied: apache-airflow-providers-common-sql in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (1.10.0)
Requirement already satisfied: apache-airflow-providers-ftp in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (3.7.0)
Requirement already satisfied: apache-airflow-providers-http in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (4.8.0)
Requirement already satisfied: apache-airflow-providers-imap in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (3.5.0)
Requirement already satisfied: apache-airflow-providers-sqlite in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow==2.8.1) (3.7.0)
Requirement already satisfied: apispec<7,>=6.0.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apispec[yaml]<7,>=6.0.0->flask-appbuilder==4.3.10->apache-airflow==2.8.1) (6.4.0)
Requirement already satisfied: colorama<1,>=0.3.9 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from flask-appbuilder==4.3.10->apache-airflow==2.8.1) (0.4.6)
Requirement already satisfied: click<9,>=8 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from flask-appbuilder==4.3.10->apache-airflow==2.8.1) (8.1.7)
Requirement already satisfied: email-validator<2,>=1.0.5 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from flask-appbuilder==4.3.10->apache-airflow==2.8.1) (1.3.1)
Requirement already satisfied: Flask-Babel<3,>=1 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from flask-appbuilder==4.3.10->apache-airflow==2.8.1) (2.0.0)
Requirement already satisfied: Flask-Limiter<4,>3 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from flask-appbuilder==4.3.10->apache-airflow==2.8.1) (3.5.0)
Requirement already satisfied: Flask-SQLAlchemy<3,>=2.4 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from flask-appbuilder==4.3.10->apache-airflow==2.8.1) (2.5.1)
Requirement already satisfied: Flask-JWT-Extended<5.0.0,>=4.0.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from flask-appbuilder==4.3.10->apache-airflow==2.8.1) (4.6.0)
Requirement already satisfied: marshmallow<4,>=3.18.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from flask-appbuilder==4.3.10->apache-airflow==2.8.1) (3.20.2)
Requirement already satisfied: marshmallow-sqlalchemy<0.27.0,>=0.22.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from flask-appbuilder==4.3.10->apache-airflow==2.8.1) (0.26.1)
Requirement already satisfied: prison<1.0.0,>=0.2.1 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from flask-appbuilder==4.3.10->apache-airflow==2.8.1) (0.2.1)
Requirement already satisfied: sqlalchemy-utils<1,>=0.32.21 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from flask-appbuilder==4.3.10->apache-airflow==2.8.1) (0.41.1)
Requirement already satisfied: WTForms<4 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from flask-appbuilder==4.3.10->apache-airflow==2.8.1) (3.1.2)
Requirement already satisfied: Mako in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from alembic<2.0,>=1.6.3->apache-airflow==2.8.1) (1.3.0)
Requirement already satisfied: typing-extensions>=4 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from alembic<2.0,>=1.6.3->apache-airflow==2.8.1) (4.9.0)
Requirement already satisfied: PyYAML>=3.10 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apispec[yaml]<7,>=6.0.0->flask-appbuilder==4.3.10->apache-airflow==2.8.1) (6.0.1)
Requirement already satisfied: clickclick<21,>=1.2 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from connexion<3.0,>=2.10.0->connexion[flask]<3.0,>=2.10.0->apache-airflow==2.8.1) (20.10.2)
Requirement already satisfied: requests<3,>=2.9.1 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from connexion<3.0,>=2.10.0->connexion[flask]<3.0,>=2.10.0->apache-airflow==2.8.1) (2.31.0)
Requirement already satisfied: inflection<0.6,>=0.3.1 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from connexion<3.0,>=2.10.0->connexion[flask]<3.0,>=2.10.0->apache-airflow==2.8.1) (0.5.1)
Requirement already satisfied: dnspython>=1.15.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from email-validator<2,>=1.0.5->flask-appbuilder==4.3.10->apache-airflow==2.8.1) (2.4.2)
Requirement already satisfied: idna>=2.0.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from email-validator<2,>=1.0.5->flask-appbuilder==4.3.10->apache-airflow==2.8.1) (3.6)
Requirement already satisfied: pytz in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from Flask-Babel<3,>=1->flask-appbuilder==4.3.10->apache-airflow==2.8.1) (2023.3.post1)
Requirement already satisfied: Babel>=2.3 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from Flask-Babel<3,>=1->flask-appbuilder==4.3.10->apache-airflow==2.8.1) (2.14.0)
Requirement already satisfied: limits>=2.8 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from Flask-Limiter<4,>3->flask-appbuilder==4.3.10->apache-airflow==2.8.1) (3.7.0)
Requirement already satisfied: ordered-set<5,>4 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from Flask-Limiter<4,>3->flask-appbuilder==4.3.10->apache-airflow==2.8.1) (4.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from jsonschema>=4.18.0->apache-airflow==2.8.1) (2023.12.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from jsonschema>=4.18.0->apache-airflow==2.8.1) (0.32.1)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from jsonschema>=4.18.0->apache-airflow==2.8.1) (0.17.1)
Collecting tzdata>=2020.1 (from pendulum<4.0,>=2.1.2->apache-airflow==2.8.1)
  Using cached tzdata-2023.4-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: time-machine>=2.6.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from pendulum<4.0,>=2.1.2->apache-airflow==2.8.1) (2.13.0)
Collecting six (from prison<1.0.0,>=0.2.1->flask-appbuilder==4.3.10->apache-airflow==2.8.1)
  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from requests<3,>=2.9.1->connexion<3.0,>=2.10.0->connexion[flask]<3.0,>=2.10.0->apache-airflow==2.8.1) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from requests<3,>=2.9.1->connexion<3.0,>=2.10.0->connexion[flask]<3.0,>=2.10.0->apache-airflow==2.8.1) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from requests<3,>=2.9.1->connexion<3.0,>=2.10.0->connexion[flask]<3.0,>=2.10.0->apache-airflow==2.8.1) (2023.11.17)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from sqlalchemy<2.0,>=1.4.28->apache-airflow==2.8.1) (3.0.3)
Requirement already satisfied: cffi>=1.12 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from cryptography>=0.9.3->apache-airflow==2.8.1) (1.16.0)
Requirement already satisfied: pycparser in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from cffi>=1.12->cryptography>=0.9.3->apache-airflow==2.8.1) (2.21)
Requirement already satisfied: wrapt<2,>=1.10 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from deprecated>=1.2.13->apache-airflow==2.8.1) (1.16.0)
Requirement already satisfied: cachelib<0.10.0,>=0.9.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from flask-caching>=1.5.0->apache-airflow==2.8.1) (0.9.0)
Requirement already satisfied: importlib-resources>=1.3 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from limits>=2.8->Flask-Limiter<4,>3->flask-appbuilder==4.3.10->apache-airflow==2.8.1) (6.1.1)
Requirement already satisfied: uc-micro-py in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from linkify-it-py>=2.0.0->apache-airflow==2.8.1) (1.0.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from markdown-it-py>=2.1.0->apache-airflow==2.8.1) (0.1.2)
Requirement already satisfied: importlib-metadata<7.0,>=6.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from opentelemetry-api>=1.15.0->apache-airflow==2.8.1) (6.11.0)
Requirement already satisfied: zipp>=0.5 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from importlib-metadata<7.0,>=6.0->opentelemetry-api>=1.15.0->apache-airflow==2.8.1) (3.17.0)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from pydantic>=2.3.0->apache-airflow==2.8.1) (0.6.0)
Requirement already satisfied: pydantic-core==2.14.6 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from pydantic>=2.3.0->apache-airflow==2.8.1) (2.14.6)
Requirement already satisfied: docutils in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from python-daemon>=3.0.0->apache-airflow==2.8.1) (0.20.1)
Requirement already satisfied: setuptools>=62.4.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from python-daemon>=3.0.0->apache-airflow==2.8.1) (80.9.0)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from python-slugify>=5.0->apache-airflow==2.8.1) (1.3)
Requirement already satisfied: sqlparse>=0.4.2 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow-providers-common-sql->apache-airflow==2.8.1) (0.4.4)
Requirement already satisfied: aiohttp in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow-providers-http->apache-airflow==2.8.1) (3.9.1)
Requirement already satisfied: requests_toolbelt in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from apache-airflow-providers-http->apache-airflow==2.8.1) (1.0.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from aiohttp->apache-airflow-providers-http->apache-airflow==2.8.1) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from aiohttp->apache-airflow-providers-http->apache-airflow==2.8.1) (1.9.4)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from aiohttp->apache-airflow-providers-http->apache-airflow==2.8.1) (1.4.1)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from aiohttp->apache-airflow-providers-http->apache-airflow==2.8.1) (1.3.1)
Requirement already satisfied: httpcore<0.17.0,>=0.15.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from httpx->apache-airflow==2.8.1) (0.16.3)
Requirement already satisfied: rfc3986<2,>=1.3 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from rfc3986[idna2008]<2,>=1.3->httpx->apache-airflow==2.8.1) (1.5.0)
Requirement already satisfied: sniffio in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from httpx->apache-airflow==2.8.1) (1.3.0)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from httpcore<0.17.0,>=0.15.0->httpx->apache-airflow==2.8.1) (0.14.0)
Requirement already satisfied: anyio<5.0,>=3.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from httpcore<0.17.0,>=0.15.0->httpx->apache-airflow==2.8.1) (4.2.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc==1.22.0 in c:\users\hi\.conda\envs\moh_s\lib\site-packages (from opentelemetry-exporter-otlp->apache-airflow==2.8.1) (1.22.0)

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython-sql 0.4.1 requires prettytable<1, but you have prettytable 3.17.0 which is incompatible.

In [10]:
import pandas as pd
import pyarrow
import duckdb
import boto3
import importlib.metadata

print("✅ pandas     :", pd.__version__)
print("✅ pyarrow    :", pyarrow.__version__)
print("✅ duckdb     :", duckdb.__version__)
print("✅ boto3      :", boto3.__version__)
print("✅ slack_sdk :", importlib.metadata.version("slack_sdk"))
print("\n🎉 All libraries loaded successfully!")

✅ pandas     : 3.0.1
✅ pyarrow    : 23.0.1
✅ duckdb     : 1.5.1
✅ boto3      : 1.28.0
✅ slack_sdk : 3.27.1

🎉 All libraries loaded successfully!

In [11]:
!pip install --force-reinstall --no-cache-dir pandas pyarrow duckdb

Collecting pandas
  Downloading pandas-3.0.2-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting pyarrow
  Downloading pyarrow-23.0.1-cp311-cp311-win_amd64.whl.metadata (3.1 kB)
Collecting duckdb
  Downloading duckdb-1.5.1-cp311-cp311-win_amd64.whl.metadata (4.2 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.4-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Collecting python-dateutil>=2.8.2 (from pandas)
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting tzdata (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas)
  Downloading six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Downloading pandas-3.0.2-cp311-cp311-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 840.2 kB/s eta 0:00:12
   -- ------------------------------------- 0.5/9.9 MB 840.2 kB/s eta 0:00:12
   ------ --------------------------------- 1.6/9.9 MB 1.5 MB/s eta 0:00:06
   ------- -------------------------------- 1.8/9.9 MB 1.5 MB/s eta 0:00:06
   -------- ------------------------------- 2.1/9.9 MB 1.6 MB/s eta 0:00:05
   ---------- ----------------------------- 2.6/9.9 MB 1.6 MB/s eta 0:00:05
   ------------ --------------------------- 3.1/9.9 MB 1.7 MB/s eta 0:00:05
   ------------- -------------------------- 3.4/9.9 MB 1.7 MB/s eta 0:00:04
   --------------- ------------------------ 3.9/9.9 MB 1.7 MB/s eta 0:00:04
   ------------------ --------------------- 4.5/9.9 MB 1.8 MB/s eta 0:00:04
   -------------------- ------------------- 5.0/9.9 MB 1.8 MB/s eta 0:00:03
   ---------------------- ----------------- 5.5/9.9 MB 1.8 MB/s eta 0:00:03
   ------------------------ --------------- 6.0/9.9 MB 1.9 MB/s eta 0:00:03
   -------------------------- ------------- 6.6/9.9 MB 1.9 MB/s eta 0:00:02
   ---------------------------- ----------- 7.1/9.9 MB 1.9 MB/s eta 0:00:02
   ------------------------------- -------- 7.9/9.9 MB 2.0 MB/s eta 0:00:02
   --------------------------------- ------ 8.4/9.9 MB 2.0 MB/s eta 0:00:01
   ---------------------------------- ----- 8.7/9.9 MB 2.0 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.9 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 2.0 MB/s  0:00:05
Downloading pyarrow-23.0.1-cp311-cp311-win_amd64.whl (27.5 MB)
   ---------------------------------------- 0.0/27.5 MB ? eta -:--:--
    --------------------------------------- 0.5/27.5 MB 2.8 MB/s eta 0:00:10
   - -------------------------------------- 1.0/27.5 MB 2.0 MB/s eta 0:00:14
   - -------------------------------------- 1.3/27.5 MB 1.7 MB/s eta 0:00:16
   -- ------------------------------------- 1.6/27.5 MB 1.9 MB/s eta 0:00:14
   --- ------------------------------------ 2.1/27.5 MB 1.9 MB/s eta 0:00:14
   ---- ----------------------------------- 2.9/27.5 MB 2.1 MB/s eta 0:00:12
   ---- ----------------------------------- 3.1/27.5 MB 2.1 MB/s eta 0:00:12
   ----- ---------------------------------- 3.7/27.5 MB 2.1 MB/s eta 0:00:12
   ------ --------------------------------- 4.2/27.5 MB 2.1 MB/s eta 0:00:12
   ------ --------------------------------- 4.7/27.5 MB 2.1 MB/s eta 0:00:11
   ------- -------------------------------- 5.2/27.5 MB 2.1 MB/s eta 0:00:11
   -------- ------------------------------- 5.8/27.5 MB 2.2 MB/s eta 0:00:11
   --------- ------------------------------ 6.3/27.5 MB 2.2 MB/s eta 0:00:10
   --------- ------------------------------ 6.8/27.5 MB 2.2 MB/s eta 0:00:10
   ---------- ----------------------------- 7.3/27.5 MB 2.2 MB/s eta 0:00:10
   ----------- ---------------------------- 7.6/27.5 MB 2.2 MB/s eta 0:00:10
   ----------- ---------------------------- 8.1/27.5 MB 2.2 MB/s eta 0:00:09
   ------------ --------------------------- 8.7/27.5 MB 2.2 MB/s eta 0:00:09
   ------------- -------------------------- 9.2/27.5 MB 2.2 MB/s eta 0:00:09
   -------------- ------------------------- 9.7/27.5 MB 2.2 MB/s eta 0:00:09
   -------------- ------------------------- 10.2/27.5 MB 2.2 MB/s eta 0:00:08
   --------------- ------------------------ 10.7/27.5 MB 2.2 MB/s eta 0:00:08
   ---------------- ----------------------- 11.3/27.5 MB 2.2 MB/s eta 0:00:08
   ----------------- ---------------------- 11.8/27.5 MB 2.2 MB/s eta 0:00:08
   ----------------- ---------------------- 12.3/27.5 MB 2.2 MB/s eta 0:00:07
   ------------------ --------------------- 12.8/27.5 MB 2.2 MB/s eta 0:00:07
   ------------------- -------------------- 13.4/27.5 MB 2.2 MB/s eta 0:00:07
   -------------------- ------------------- 13.9/27.5 MB 2.2 MB/s eta 0:00:07
   --------------------- ------------------ 14.7/27.5 MB 2.3 MB/s eta 0:00:06
   ---------------------- ----------------- 15.2/27.5 MB 2.3 MB/s eta 0:00:06
   ---------------------- ----------------- 15.7/27.5 MB 2.3 MB/s eta 0:00:06
   ----------------------- ---------------- 16.3/27.5 MB 2.3 MB/s eta 0:00:05
   ------------------------ --------------- 16.8/27.5 MB 2.3 MB/s eta 0:00:05
   ------------------------ --------------- 17.0/27.5 MB 2.3 MB/s eta 0:00:05
   ------------------------- -------------- 17.8/27.5 MB 2.3 MB/s eta 0:00:05
   ------------------------- -------------- 17.8/27.5 MB 2.3 MB/s eta 0:00:05
   --------------------------- ------------ 18.6/27.5 MB 2.3 MB/s eta 0:00:04
   --------------------------- ------------ 19.1/27.5 MB 2.3 MB/s eta 0:00:04
   ---------------------------- ----------- 19.7/27.5 MB 2.3 MB/s eta 0:00:04
   ----------------------------- ---------- 20.2/27.5 MB 2.3 MB/s eta 0:00:04
   ------------------------------ --------- 21.0/27.5 MB 2.3 MB/s eta 0:00:03
   ------------------------------- -------- 21.8/27.5 MB 2.3 MB/s eta 0:00:03
   -------------------------------- ------- 22.5/27.5 MB 2.3 MB/s eta 0:00:03
   --------------------------------- ------ 23.1/27.5 MB 2.4 MB/s eta 0:00:02
   ---------------------------------- ----- 23.9/27.5 MB 2.4 MB/s eta 0:00:02
   ----------------------------------- ---- 24.6/27.5 MB 2.4 MB/s eta 0:00:02
   ------------------------------------ --- 25.2/27.5 MB 2.4 MB/s eta 0:00:01
   ------------------------------------- -- 26.0/27.5 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  27.0/27.5 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 27.5/27.5 MB 2.5 MB/s  0:00:11
Downloading duckdb-1.5.1-cp311-cp311-win_amd64.whl (13.1 MB)
   ---------------------------------------- 0.0/13.1 MB ? eta -:--:--
   -- ------------------------------------- 0.8/13.1 MB 5.6 MB/s eta 0:00:03
   --- ------------------------------------ 1.0/13.1 MB 2.2 MB/s eta 0:00:06
   ------ --------------------------------- 2.1/13.1 MB 2.9 MB/s eta 0:00:04
   -------- ------------------------------- 2.9/13.1 MB 3.2 MB/s eta 0:00:04
   ------------ --------------------------- 3.9/13.1 MB 3.4 MB/s eta 0:00:03
   -------------- ------------------------- 4.7/13.1 MB 3.5 MB/s eta 0:00:03
   ----------------- ---------------------- 5.8/13.1 MB 3.6 MB/s eta 0:00:03
   -------------------- ------------------- 6.8/13.1 MB 3.7 MB/s eta 0:00:02
   ----------------------- ---------------- 7.6/13.1 MB 3.7 MB/s eta 0:00:02
   -------------------------- ------------- 8.7/13.1 MB 3.8 MB/s eta 0:00:02
   ----------------------------- ---------- 9.7/13.1 MB 3.9 MB/s eta 0:00:01
   -------------------------------- ------- 10.7/13.1 MB 4.0 MB/s eta 0:00:01
   ------------------------------------ --- 11.8/13.1 MB 4.1 MB/s eta 0:00:01
   ---------------------------------------- 13.1/13.1 MB 4.1 MB/s  0:00:03
Downloading numpy-2.4.4-cp311-cp311-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.6 MB 6.1 MB/s eta 0:00:02
   ------- -------------------------------- 2.4/12.6 MB 5.2 MB/s eta 0:00:02
   ---------- ----------------------------- 3.4/12.6 MB 5.3 MB/s eta 0:00:02
   -------------- ------------------------- 4.7/12.6 MB 5.3 MB/s eta 0:00:02
   ------------------ --------------------- 5.8/12.6 MB 5.1 MB/s eta 0:00:02
   --------------------- ------------------ 6.8/12.6 MB 5.1 MB/s eta 0:00:02
   ------------------------- -------------- 8.1/12.6 MB 5.2 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.6 MB 5.1 MB/s eta 0:00:01
   -------------------------------- ------- 10.2/12.6 MB 5.0 MB/s eta 0:00:01
   ---------------------------------- ----- 11.0/12.6 MB 4.9 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.6 MB 4.8 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.6 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 4.2 MB/s  0:00:02
Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, six, pyarrow, numpy, duckdb, python-dateutil, pandas

  Attempting uninstall: tzdata

    Found existing installation: tzdata 2023.4

   ---------------------------------------- 0/7 [tzdata]
   ---------------------------------------- 0/7 [tzdata]
    Uninstalling tzdata-2023.4:
   ---------------------------------------- 0/7 [tzdata]
      Successfully uninstalled tzdata-2023.4
   ---------------------------------------- 0/7 [tzdata]
   ---------------------------------------- 0/7 [tzdata]
   ---------------------------------------- 0/7 [tzdata]
   ---------------------------------------- 0/7 [tzdata]
   ---------------------------------------- 0/7 [tzdata]
   ---------------------------------------- 0/7 [tzdata]
   ---------------------------------------- 0/7 [tzdata]
   ---------------------------------------- 0/7 [tzdata]
   ---------------------------------------- 0/7 [tzdata]
   ---------------------------------------- 0/7 [tzdata]
  Attempting uninstall: six
   ---------------------------------------- 0/7 [tzdata]
    Found existing installation: six 1.16.0
   ---------------------------------------- 0/7 [tzdata]
    Uninstalling six-1.16.0:
   ---------------------------------------- 0/7 [tzdata]
   ----- ---------------------------------- 1/7 [six]
   ----- ---------------------------------- 1/7 [six]
   ----- ---------------------------------- 1/7 [six]
   ----- ---------------------------------- 1/7 [six]
   ----- ---------------------------------- 1/7 [six]
   ----- ---------------------------------- 1/7 [six]
   ----- ---------------------------------- 1/7 [six]
   ----- ---------------------------------- 1/7 [six]
   ----- ---------------------------------- 1/7 [six]
   ----- ---------------------------------- 1/7 [six]
   ----- ---------------------------------- 1/7 [six]
   ----- ---------------------------------- 1/7 [six]
   ----- ---------------------------------- 1/7 [six]
   ----- ---------------------------------- 1/7 [six]
   ----- ---------------------------------- 1/7 [six]
   ----- ---------------------------------- 1/7 [six]
   ----- ---------------------------------- 1/7 [six]
      Successfully uninstalled six-1.16.0
   ----- ---------------------------------- 1/7 [six]
   ----- ---------------------------------- 1/7 [six]
   ----- ---------------------------------- 1/7 [six]
  Attempting uninstall: pyarrow
   ----- ---------------------------------- 1/7 [six]
    Found existing installation: pyarrow 14.0.1
   ----- ---------------------------------- 1/7 [six]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
    Uninstalling pyarrow-14.0.1:
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
      Successfully uninstalled pyarrow-14.0.1
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------- ---------------------------- 2/7 [pyarrow]
  Attempting uninstall: numpy
   ----------- ---------------------------- 2/7 [pyarrow]
   ----------------- ---------------------- 3/7 [numpy]
    Found existing installation: numpy 2.4.3
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
    Uninstalling numpy-2.4.3:
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
      Successfully uninstalled numpy-2.4.3
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]
   ----------------- ---------------------- 3/7 [numpy]

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Hi\.conda\envs\moh_S\Lib\site-packages\~~mpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Hi\.conda\envs\moh_S\Lib\site-packages\~.mpy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython-sql 0.4.1 requires prettytable<1, but you have prettytable 3.17.0 which is incompatible.

In [1]:
import os

folders = [
    "data/raw",
    "data/processed",
    "scripts",
    "dags",
    "dashboards",
    "docs",
    "airflow"
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)
    print(f"✅ Created → {folder}")

print("\n📁 Project structure ready!")
print("""
fintech-behavior-analytics/
├── data/
│   ├── raw/
│   └── processed/
├── scripts/
├── dags/
├── dashboards/
├── docs/
├── airflow/
└── fintech_analytics.ipynb
""")

✅ Created → data/raw
✅ Created → data/processed
✅ Created → scripts
✅ Created → dags
✅ Created → dashboards
✅ Created → docs
✅ Created → airflow

📁 Project structure ready!

fintech-behavior-analytics/
├── data/
│   ├── raw/
│   └── processed/
├── scripts/
├── dags/
├── dashboards/
├── docs/
├── airflow/
└── fintech_analytics.ipynb

In [6]:
gitignore_content = """
.env
airflow/logs/
airflow/db/
__pycache__/
*.pyc
""".strip()

with open(".gitignore", "w") as f:
    f.write(gitignore_content)

print("✅ .gitignore created!")
print("\nContents:")
print(gitignore_content)

✅ .gitignore created!

Contents:
.env
airflow/logs/
airflow/db/
__pycache__/
*.pyc

In [9]:
!git add .
!git commit -m "Cleanup: remove .gitkeep from data folder"
!git push

[main 1172154] Cleanup: remove .gitkeep from data folder
 1 file changed, 0 insertions(+), 0 deletions(-)
 delete mode 100644 data/.gitkeep

To https://github.com/mohimpact/fintech-behavior-analytics.git
   1b8e48b..1172154  main -> main

In [14]:
requirements = """
pandas==2.1.0
boto3==1.28.0
python-dotenv==1.0.0
duckdb==0.10.0
pyarrow==14.0.1
apache-airflow==2.8.1
slack-sdk==3.27.1
""".strip()

with open("requirements.txt", "w") as f:
    f.write(requirements)

print("✅ requirements.txt created!")
print("\nContents:")
print(requirements)

✅ requirements.txt created!

Contents:
pandas==2.1.0
boto3==1.28.0
python-dotenv==1.0.0
duckdb==0.10.0
pyarrow==14.0.1
apache-airflow==2.8.1
slack-sdk==3.27.1

In [15]:
import duckdb

con = duckdb.connect()
result = con.execute("SELECT 'DuckDB is working!' AS message").fetchdf()
print(result)
print("\n✅ DuckDB hello world passed!")

              message
0  DuckDB is working!

✅ DuckDB hello world passed!

In [18]:
!git init

Reinitialized existing Git repository in C:/Users/Hi/Documents/Real-Time Customer Behavior Analytics Platform/.git/

In [19]:
!git add .

In [20]:
!git commit -m "Initial project setup"

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [21]:
# Replace YOUR_USERNAME with your actual GitHub username
# First create the repo on github.com, then run this

!git remote add origin https://github.com/mohimpact/fintech-behavior-analytics.git
!git push -u origin main

error: remote origin already exists.

branch 'main' set up to track 'origin/main'.

Everything up-to-date

In [22]:
!git push -u origin main

branch 'main' set up to track 'origin/main'.

Everything up-to-date

In [10]:
import pandas as pd
import numpy as np
import random
import uuid
import os
import pyarrow as pa
import pyarrow.parquet as pq
from datetime import datetime, timedelta

# ── Reproducibility seeds ──────────────────────────────────────────────────
random.seed(42)
np.random.seed(42)

# ── Configuration ──────────────────────────────────────────────────────────
NUM_USERS   = 1000
NUM_EVENTS  = 50000
DAYS        = 90
START_DATE  = datetime(2024, 1, 1)
OUTPUT_DIR  = "data/raw"

NIGERIAN_CITIES = [
    "Lagos", "Abuja", "Port Harcourt", "Kano",
    "Ibadan", "Enugu", "Kaduna", "Benin City"
]

DEVICES        = ["android", "ios", "web"]
DEVICE_WEIGHTS = [0.55, 0.30, 0.15]    # Most Nigerians use Android

EVENT_TYPES = [
    "app_open", "login", "view_dashboard", "create_savings_plan",
    "deposit_money", "withdraw_money", "check_balance", "logout"
]

# Financial events with realistic Naira amount ranges
FINANCIAL_EVENTS = {
    "deposit_money":  (2000,  500000),
    "withdraw_money": (1000,  200000),
}

print("✅ Configuration loaded!")
print(f"   Users      : {NUM_USERS:,}")
print(f"   Events     : {NUM_EVENTS:,}")
print(f"   Date range : {START_DATE.date()} → {(START_DATE + timedelta(days=DAYS)).date()}")
print(f"   Cities     : {NIGERIAN_CITIES}")

✅ Configuration loaded!
   Users      : 1,000
   Events     : 50,000
   Date range : 2024-01-01 → 2024-03-31
   Cities     : ['Lagos', 'Abuja', 'Port Harcourt', 'Kano', 'Ibadan', 'Enugu', 'Kaduna', 'Benin City']

In [21]:
def create_user_profiles(num_users: int) -> pd.DataFrame:
    """
    Create user profiles with 3 realistic segments:
    - 70% lurkers  → low activity (open app rarely)
    - 20% regular  → weekly activity
    - 10% power    → daily activity
    """
    profiles = []

    for i in range(num_users):
        rand = random.random()

        if rand < 0.70:
            segment        = "lurker"
            events_per_day = np.random.uniform(0.05, 0.3)   # less than 1 event/day
        elif rand < 0.90:
            segment        = "regular"
            events_per_day = np.random.uniform(0.5, 2.0)    # a few times per week
        else:
            segment        = "power"
            events_per_day = np.random.uniform(3.0, 8.0)    # multiple times per day

        profiles.append({
            "user_id":        f"USR{i+1:05d}",
            "segment":        segment,
            "events_per_day": events_per_day,
            "city":           random.choice(NIGERIAN_CITIES),
            "device":         random.choices(DEVICES, weights=DEVICE_WEIGHTS)[0],
            "tenure_days":    random.randint(1, 365),
            "join_date":      START_DATE - timedelta(days=random.randint(1, 365)),
        })

    return pd.DataFrame(profiles)


# ── Run & preview ──────────────────────────────────────────────────────────
users_df = create_user_profiles(NUM_USERS)

print(f"✅ Created {len(users_df):,} user profiles\n")
print("Segment breakdown:")
print(users_df["segment"].value_counts())
print(f"\nSample profiles:")
users_df.head(5)

✅ Created 1,000 user profiles

Segment breakdown:
segment
lurker     697
regular    204
power       99
Name: count, dtype: int64

Sample profiles:

    user_id segment  events_per_day   city   device  tenure_days  join_date
0  USR00001  lurker        0.143635  Lagos      ios          126 2023-09-08
1  USR00002  lurker        0.287679  Abuja      ios          280 2023-11-17
2  USR00003  lurker        0.232998  Lagos  android          112 2023-09-03
3  USR00004  lurker        0.199665  Lagos      ios          333 2023-01-06
4  USR00005  lurker        0.089005   Kano  android          143 2023-12-28

In [22]:
def realistic_timestamp(base_date: datetime) -> datetime:
    """
    Generate timestamps with realistic Nigerian time-of-day patterns.
    Peak hours: 8am (commute), 12pm (lunch), 6pm (evening)
    Weekends have ~30% less activity than weekdays.
    """
    hour_weights = [
        0.5, 0.3, 0.2, 0.2, 0.3, 0.5,    # 12am–5am  (very low)
        1.0, 1.5, 3.0, 2.5, 2.0, 2.5,    # 6am–11am  (morning peak at 8am)
        3.5, 2.5, 2.0, 2.0, 2.5, 3.5,    # 12pm–5pm  (lunch peak)
        4.0, 3.5, 2.5, 2.0, 1.5, 1.0,    # 6pm–11pm  (evening peak)
    ]

    hour   = random.choices(range(24), weights=hour_weights)[0]
    minute = random.randint(0, 59)
    second = random.randint(0, 59)

    ts = base_date.replace(hour=hour, minute=minute, second=second)

    # Weekend reduction — shift 30% of weekend events to weekdays
    if ts.weekday() >= 5:
        if random.random() < 0.30:
            ts = ts - timedelta(days=random.randint(1, 2))

    return ts


# ── Quick test ─────────────────────────────────────────────────────────────
test_ts = realistic_timestamp(datetime(2024, 1, 15))
print(f"✅ Timestamp generator working")
print(f"   Sample timestamp : {test_ts}")
print(f"   Day of week      : {test_ts.strftime('%A')}")
print(f"   Hour             : {test_ts.hour}:00")

✅ Timestamp generator working
   Sample timestamp : 2024-01-15 09:26:19
   Day of week      : Monday
   Hour             : 9:00

In [23]:
def build_event(user: dict, event_type: str, ts: datetime, session_id: str) -> dict:
    """Build a single event record with all required fields."""
    amount = None
    if event_type in FINANCIAL_EVENTS:
        lo, hi = FINANCIAL_EVENTS[event_type]
        amount = round(random.uniform(lo, hi), 2)

    return {
        "event_id":         str(uuid.uuid4()),
        "user_id":          user["user_id"],
        "event_type":       event_type,
        "timestamp":        ts,
        "amount":           amount,
        "session_id":       session_id,
        "device_type":      user["device"],
        "location_city":    user["city"],
        "user_tenure_days": user["tenure_days"],
        "user_segment":     user["segment"],
    }


def generate_session_events(user: dict, session_date: datetime) -> list:
    """
    Generate a realistic sequence of events for one user session.
    Flow: app_open → login → (actions) → logout
    """
    session_id = str(uuid.uuid4())[:8]
    events     = []
    ts         = realistic_timestamp(session_date)

    # Every session starts with app_open then login
    for event_type in ["app_open", "login"]:
        events.append(build_event(user, event_type, ts, session_id))
        ts += timedelta(seconds=random.randint(2, 10))

    # Number of middle actions depends on segment
    if user["segment"] == "power":
        num_actions = random.randint(2, 4)
    elif user["segment"] == "regular":
        num_actions = random.randint(1, 3)
    else:
        num_actions = random.randint(1, 2)

    # Middle actions with realistic weights
    mid_actions = [
        "view_dashboard", "check_balance",
        "create_savings_plan", "deposit_money", "withdraw_money"
    ]
    mid_weights = [0.35, 0.30, 0.15, 0.13, 0.07]

    for _ in range(num_actions):
        action = random.choices(mid_actions, weights=mid_weights)[0]
        events.append(build_event(user, action, ts, session_id))
        ts += timedelta(seconds=random.randint(15, 120))

    # 80% of sessions end with an explicit logout
    if random.random() < 0.80:
        events.append(build_event(user, "logout", ts, session_id))

    return events


print("✅ Event builder functions ready!")
print("   build_event()            → builds one event record")
print("   generate_session_events() → builds a full session flow")

✅ Event builder functions ready!
   build_event()            → builds one event record
   generate_session_events() → builds a full session flow

In [24]:
def generate_events(num_events: int = NUM_EVENTS) -> pd.DataFrame:
    """Generate all events across all users over the 90-day window."""

    print("Step 1: Creating user profiles...")
    users_df     = create_user_profiles(NUM_USERS)
    users        = users_df.to_dict("records")
    total_weight = users_df["events_per_day"].sum()

    print(f"Step 2: Generating ~{num_events:,} events over {DAYS} days...")
    all_events = []

    for user in users:
        # Calculate how many sessions this user gets over 90 days
        expected_sessions = int(
            (user["events_per_day"] / total_weight) * num_events / 3
        )
        expected_sessions = max(1, expected_sessions)

        # Randomly spread sessions across the 90-day window
        session_days = sorted(
            random.choices(range(DAYS), k=expected_sessions)
        )

        for day_offset in session_days:
            session_date = START_DATE + timedelta(days=day_offset)
            events       = generate_session_events(user, session_date)
            all_events.extend(events)

        # Stop once we hit our target
        if len(all_events) >= num_events:
            break

    # Build DataFrame, sort by time, trim to exact target
    df = pd.DataFrame(all_events)
    df = df.sort_values("timestamp").reset_index(drop=True)
    df = df.head(num_events)

    print(f"\n✅ Generated {len(df):,} events")
    print(f"   Date range    : {df['timestamp'].min().date()} → {df['timestamp'].max().date()}")
    print(f"   Unique users  : {df['user_id'].nunique():,}")
    print(f"   Unique sessions: {df['session_id'].nunique():,}")
    print(f"\n   Event type breakdown:")
    print(df["event_type"].value_counts().to_string())

    return df


# ── Run it ─────────────────────────────────────────────────────────────────
events_df = generate_events(NUM_EVENTS)
print(f"\nPreview of first 5 rows:")
events_df.head()

Step 1: Creating user profiles...
Step 2: Generating ~50,000 events over 90 days...

✅ Generated 50,000 events
   Date range    : 2024-01-01 → 2024-03-30
   Unique users  : 572
   Unique sessions: 9,293

   Event type breakdown:
event_type
app_open               9293
login                  9292
view_dashboard         8387
logout                 7420
check_balance          7138
create_savings_plan    3623
deposit_money          3203
withdraw_money         1644

Preview of first 5 rows:

,event_id,user_id,event_type,timestamp,amount,session_id,device_type,location_city,user_tenure_days,user_segment
0,18c84fed-8cee-4d7b-a95c-9b94886be45b,USR00339,app_open,2024-01-01 05:40:58,NaN,111b2375,android,Port Harcourt,190,power
1,7161298c-8bf2-4a25-9160-9834a12183c5,USR00339,login,2024-01-01 05:41:04,NaN,111b2375,android,Port Harcourt,190,power
2,e40835c3-d03a-4bae-aabf-e34e00bf1e6a,USR00339,deposit_money,2024-01-01 05:41:08,231685.7,111b2375,android,Port Harcourt,190,power
3,d105dc25-f25e-403e-b55c-c05cb12f7f49,USR00339,check_balance,2024-01-01 05:41:52,NaN,111b2375,android,Port Harcourt,190,power
4,39cf8b22-e7f7-41ae-b8e7-a74c79db9a7c,USR00339,view_dashboard,2024-01-01 05:42:26,NaN,111b2375,android,Port Harcourt,190,power

In [25]:
def save_partitioned_parquet(df: pd.DataFrame, output_dir: str = OUTPUT_DIR):
    """
    Save events partitioned by year/month/day.
    Mirrors real production data lake structure:
    data/raw/year=2024/month=01/day=01/events.parquet
    """
    df = df.copy()
    df["year"]  = df["timestamp"].dt.year.astype(str)
    df["month"] = df["timestamp"].dt.month.apply(lambda x: f"{x:02d}")
    df["day"]   = df["timestamp"].dt.day.apply(lambda x: f"{x:02d}")

    groups = df.groupby(["year", "month", "day"])
    print(f"Saving {len(groups)} daily partition files...")

    for (year, month, day), group in groups:
        partition_path = os.path.join(
            output_dir,
            f"year={year}",
            f"month={month}",
            f"day={day}"
        )
        os.makedirs(partition_path, exist_ok=True)

        file_path = os.path.join(partition_path, "events.parquet")
        group.drop(columns=["year", "month", "day"]).to_parquet(
            file_path, index=False
        )

    print(f"\n✅ Partitioned files saved to {output_dir}/")
    print(f"   Total daily partitions : {len(groups)}")
    print(f"   Example path           : {output_dir}/year=2024/month=01/day=01/events.parquet")


# ── Run it ─────────────────────────────────────────────────────────────────
os.makedirs(OUTPUT_DIR, exist_ok=True)
save_partitioned_parquet(events_df)

Saving 90 daily partition files...

✅ Partitioned files saved to data/raw/
   Total daily partitions : 90
   Example path           : data/raw/year=2024/month=01/day=01/events.parquet

In [26]:
def save_flat_parquet(df: pd.DataFrame):
    """
    Save a single flat parquet file.
    This is what we'll load into Power BI later.
    """
    flat_path = "data/processed/events_flat.parquet"
    os.makedirs("data/processed", exist_ok=True)
    df.to_parquet(flat_path, index=False)

    size_kb = os.path.getsize(flat_path) / 1024
    print(f"✅ Flat file saved → {flat_path}")
    print(f"   Rows  : {len(df):,}")
    print(f"   Cols  : {len(df.columns)}")
    print(f"   Size  : {size_kb:.1f} KB")


# ── Run it ─────────────────────────────────────────────────────────────────
save_flat_parquet(events_df)

✅ Flat file saved → data/processed/events_flat.parquet
   Rows  : 50,000
   Cols  : 10
   Size  : 2551.6 KB

In [27]:
import duckdb

con = duckdb.connect()

print("=== Event Type Summary ===")
event_summary = con.execute("""
    SELECT
        event_type,
        COUNT(*)                    AS total_events,
        COUNT(DISTINCT user_id)     AS unique_users,
        COUNT(DISTINCT session_id)  AS unique_sessions,
        ROUND(AVG(amount), 2)       AS avg_amount_naira
    FROM read_parquet('data/raw/**/*.parquet')
    GROUP BY event_type
    ORDER BY total_events DESC
""").fetchdf()

event_summary

=== Event Type Summary ===

,event_type,total_events,unique_users,unique_sessions,avg_amount_naira
0,app_open,9293,572,9293,NaN
1,login,9292,572,9292,NaN
2,view_dashboard,8387,461,5985,NaN
3,logout,7420,548,7420,NaN
4,check_balance,7138,451,5336,NaN
5,create_savings_plan,3623,351,3140,NaN
6,deposit_money,3203,335,2790,253966.99
7,withdraw_money,1644,267,1536,101471.29

In [28]:
print("=== User Segment Breakdown ===")
segment_summary = con.execute("""
    SELECT
        user_segment,
        COUNT(DISTINCT user_id)    AS users,
        COUNT(*)                   AS total_events,
        COUNT(DISTINCT session_id) AS total_sessions
    FROM read_parquet('data/raw/**/*.parquet')
    GROUP BY user_segment
    ORDER BY users DESC
""").fetchdf()

segment_summary

=== User Segment Breakdown ===

  user_segment  users  total_events  total_sessions
0       lurker    381          4076             953
1      regular    124         12043            2500
2        power     67         33881            5840

In [29]:
print("=== Hourly Activity Pattern ===")
hourly = con.execute("""
    SELECT
        EXTRACT(HOUR FROM timestamp) AS hour,
        COUNT(*)                     AS events
    FROM read_parquet('data/raw/**/*.parquet')
    GROUP BY hour
    ORDER BY hour
""").fetchdf()

hourly

=== Hourly Activity Pattern ===

    hour  events
0      0     621
1      1     243
2      2     196
3      3     158
4      4     302
5      5     466
6      6    1178
7      7    1742
8      8    3035
9      9    2494
10    10    2080
11    11    2650
12    12    4046
13    13    2973
14    14    2190
15    15    2155
16    16    2678
17    17    4107
18    18    4560
19    19    4239
20    20    2775
21    21    2196
22    22    1790
23    23    1126

In [30]:
print("=== Final Dataset Overview ===\n")
print(f"Shape          : {events_df.shape}")
print(f"Columns        : {list(events_df.columns)}")
print(f"Date range     : {events_df['timestamp'].min().date()} → {events_df['timestamp'].max().date()}")
print(f"Unique users   : {events_df['user_id'].nunique():,}")
print(f"Unique sessions: {events_df['session_id'].nunique():,}")
print(f"\nNull values per column:")
print(events_df.isnull().sum())
print(f"\nRandom sample of 5 rows:")
events_df.sample(5)

=== Final Dataset Overview ===

Shape          : (50000, 10)
Columns        : ['event_id', 'user_id', 'event_type', 'timestamp', 'amount', 'session_id', 'device_type', 'location_city', 'user_tenure_days', 'user_segment']
Date range     : 2024-01-01 → 2024-03-30
Unique users   : 572
Unique sessions: 9,293

Null values per column:
event_id                0
user_id                 0
event_type              0
timestamp               0
amount              45153
session_id              0
device_type             0
location_city           0
user_tenure_days        0
user_segment            0
dtype: int64

Random sample of 5 rows:

,event_id,user_id,event_type,timestamp,amount,session_id,device_type,location_city,user_tenure_days,user_segment
38783,98a9eefe-09b8-422d-9561-6e820730601c,USR00528,check_balance,2024-03-10 17:21:43,NaN,3e7850b3,android,Benin City,66,power
32961,e773dfd3-d21e-4548-949d-95fbdf2e513b,USR00256,create_savings_plan,2024-02-29 15:46:39,NaN,a571499c,android,Benin City,275,power
25636,154d230b-365a-40f0-b26c-aca2339fed08,USR00325,check_balance,2024-02-15 23:22:28,NaN,37d79de4,android,Abuja,235,power
5683,69e47383-ecf7-46a9-91a2-b3c9e0e1d08d,USR00150,deposit_money,2024-01-10 22:29:52,357486.51,7a56a63d,ios,Enugu,10,lurker
19242,b03e3861-e90d-461d-baa8-bebf4423c6a3,USR00116,check_balance,2024-02-04 14:24:01,NaN,fe56343e,ios,Port Harcourt,64,power

In [31]:
!git add .

In [32]:
!git commit -m "Days 1-4: Event generator — 50K fintech events, partitioned parquet"

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [33]:
!git push origin main

Everything up-to-date

In [34]:
!git config --global core.autocrlf true

In [1]:
# Create your .env file to store AWS credentials safely
# NEVER share this file or commit it to GitHub

env_content = """AWS_ACCESS_KEY_ID=AKIAXR6GN6OMSGMKXYHH
AWS_SECRET_ACCESS_KEY=Gm2BcLdZ1303iyHa1A16ayAu5zPpi74q57v21cIY
AWS_BUCKET_NAME=fintech-analytics-2026
AWS_REGION=eu-north-1
""".strip()

with open(".env", "w") as f:
    f.write(env_content)

print("✅ .env file created!")
print("\n⚠️  IMPORTANT NEXT STEPS:")
print("   1. Go to AWS Console → IAM → Users → Create User")
print("   2. Attach policy: AmazonS3FullAccess")
print("   3. Create Access Key → download CSV")
print("   4. Open your .env file in VS Code")
print("   5. Replace 'your_access_key_here' with your real key")
print("   6. Replace 'your_secret_key_here' with your real secret")
print("   7. Replace bucket name with YOUR bucket name")
print("\n🔒 .env is in .gitignore — it will NEVER be pushed to GitHub")

✅ .env file created!

⚠️  IMPORTANT NEXT STEPS:
   1. Go to AWS Console → IAM → Users → Create User
   2. Attach policy: AmazonS3FullAccess
   3. Create Access Key → download CSV
   4. Open your .env file in VS Code
   5. Replace 'your_access_key_here' with your real key
   6. Replace 'your_secret_key_here' with your real secret
   7. Replace bucket name with YOUR bucket name

🔒 .env is in .gitignore — it will NEVER be pushed to GitHub

In [2]:
# Run this AFTER you have updated your .env file with real keys
from dotenv import load_dotenv
import os

load_dotenv()

AWS_ACCESS_KEY    = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_KEY    = os.getenv("AWS_SECRET_ACCESS_KEY")
BUCKET_NAME       = os.getenv("AWS_BUCKET_NAME")
AWS_REGION        = os.getenv("AWS_REGION")

# Verify credentials loaded (we hide the actual values for security)
print("✅ Credentials loaded from .env")
print(f"   Access Key  : {AWS_ACCESS_KEY[:6]}... (hidden for security)")
print(f"   Secret Key  : {AWS_SECRET_KEY[:6]}... (hidden for security)")
print(f"   Bucket Name : {BUCKET_NAME}")
print(f"   Region      : {AWS_REGION}")

if "your_access_key_here" in AWS_ACCESS_KEY:
    print("\n❌ ERROR: You haven't updated your .env file yet!")
    print("   Open .env and replace the placeholder values with real keys")
else:
    print("\n🎉 Credentials look good! Move to the next cell.")

✅ Credentials loaded from .env
   Access Key  : AKIAXR... (hidden for security)
   Secret Key  : Gm2BcL... (hidden for security)
   Bucket Name : fintech-analytics-2026
   Region      : eu-north-1

🎉 Credentials look good! Move to the next cell.

In [3]:
import boto3
from botocore.exceptions import ClientError, NoCredentialsError

def test_aws_connection():
    """Test that we can connect to AWS S3 successfully."""
    try:
        s3 = boto3.client(
            "s3",
            aws_access_key_id     = AWS_ACCESS_KEY,
            aws_secret_access_key = AWS_SECRET_KEY,
            region_name           = AWS_REGION
        )

        # Try to list buckets — simplest possible S3 operation
        response = s3.list_buckets()
        buckets  = [b["Name"] for b in response["Buckets"]]

        print("✅ AWS Connection successful!")
        print(f"   Your S3 buckets: {buckets}")

        if BUCKET_NAME in buckets:
            print(f"\n✅ Target bucket '{BUCKET_NAME}' found and ready!")
        else:
            print(f"\n⚠️  Bucket '{BUCKET_NAME}' not found.")
            print(f"   Available buckets: {buckets}")
            print(f"   → Go to AWS Console and create it, OR update .env with correct name")

        return s3

    except NoCredentialsError:
        print("❌ ERROR: No credentials found.")
        print("   → Check your .env file has real keys")
    except ClientError as e:
        print(f"❌ AWS Error: {e}")
        print("   → Check your Access Key and Secret Key are correct")

s3_client = test_aws_connection()

✅ AWS Connection successful!
   Your S3 buckets: ['fintech-analytics-2026', 'umar-portfolio-2026']

✅ Target bucket 'fintech-analytics-2026' found and ready!

In [4]:
def create_s3_folder_structure(s3, bucket: str):
    folders = [
        "raw/.keep",
        "processed/.keep",
        "reports/.keep"
    ]

    print(f"Creating folder structure in s3://{bucket}/")

    for folder in folders:
        s3.put_object(Bucket=bucket, Key=folder, Body=b"")
        folder_name = folder.replace("/.keep", "/")
        print(f"   ✅ Created → s3://{bucket}/{folder_name}")

    print(f"\n✅ S3 data lake structure ready!")
    print(f"""
   s3://{bucket}/
   ├── raw/          ← partitioned event parquet files
   ├── processed/    ← daily summary parquet files
   └── reports/      ← automated insight reports
    """)

create_s3_folder_structure(s3_client, BUCKET_NAME)

Creating folder structure in s3://fintech-analytics-2026/
   ✅ Created → s3://fintech-analytics-2026/raw/
   ✅ Created → s3://fintech-analytics-2026/processed/
   ✅ Created → s3://fintech-analytics-2026/reports/

✅ S3 data lake structure ready!

   s3://fintech-analytics-2026/
   ├── raw/          ← partitioned event parquet files
   ├── processed/    ← daily summary parquet files
   └── reports/      ← automated insight reports

In [5]:
import os
from pathlib import Path

def upload_partitioned_files(s3, bucket: str, local_dir: str = "data/raw"):
    local_path    = Path(local_dir)
    parquet_files = list(local_path.rglob("*.parquet"))

    print(f"Found {len(parquet_files)} parquet files to upload...")
    print(f"Uploading to s3://{bucket}/raw/\n")

    uploaded = 0
    failed   = 0

    for file_path in parquet_files:
        relative_path = file_path.relative_to(local_path)
        s3_key        = f"raw/{relative_path}".replace("\\", "/")

        try:
            s3.upload_file(str(file_path), bucket, s3_key)
            uploaded += 1
            if uploaded % 10 == 0:
                print(f"   Uploaded {uploaded}/{len(parquet_files)} files...")
        except Exception as e:
            print(f"   ❌ Failed: {file_path} → {e}")
            failed += 1

    print(f"\n✅ Upload complete!")
    print(f"   Uploaded : {uploaded} files")
    print(f"   Failed   : {failed} files")
    print(f"   Location : s3://{bucket}/raw/")

upload_partitioned_files(s3_client, BUCKET_NAME)

Found 90 parquet files to upload...
Uploading to s3://fintech-analytics-2026/raw/

   Uploaded 10/90 files...
   Uploaded 20/90 files...
   Uploaded 30/90 files...
   Uploaded 40/90 files...
   Uploaded 50/90 files...
   Uploaded 60/90 files...
   Uploaded 70/90 files...
   Uploaded 80/90 files...
   Uploaded 90/90 files...

✅ Upload complete!
   Uploaded : 90 files
   Failed   : 0 files
   Location : s3://fintech-analytics-2026/raw/

In [6]:
def upload_flat_file(s3, bucket: str):
    local_path = "data/processed/events_flat.parquet"
    s3_key     = "processed/events_flat.parquet"

    print(f"Uploading flat file...")
    print(f"   Local → {local_path}")
    print(f"   S3    → s3://{bucket}/{s3_key}")

    try:
        s3.upload_file(local_path, bucket, s3_key)
        response = s3.head_object(Bucket=bucket, Key=s3_key)
        size_kb  = response["ContentLength"] / 1024

        print(f"\n✅ Flat file uploaded!")
        print(f"   Size : {size_kb:.1f} KB")

    except Exception as e:
        print(f"❌ Upload failed: {e}")

upload_flat_file(s3_client, BUCKET_NAME)

Uploading flat file...
   Local → data/processed/events_flat.parquet
   S3    → s3://fintech-analytics-2026/processed/events_flat.parquet

✅ Flat file uploaded!
   Size : 2551.6 KB

In [7]:
def verify_s3_contents(s3, bucket: str):
    print(f"=== Contents of s3://{bucket}/ ===\n")

    response   = s3.list_objects_v2(Bucket=bucket)
    objects    = response.get("Contents", [])

    if not objects:
        print("❌ Bucket is empty — uploads may have failed")
        return

    total_size = 0
    for obj in objects:
        size_kb     = obj["Size"] / 1024
        total_size += obj["Size"]
        print(f"   {obj['Key']:<60} {size_kb:>8.1f} KB")

    print(f"\n{'─'*70}")
    print(f"   Total files : {len(objects)}")
    print(f"   Total size  : {total_size / 1024:.1f} KB")
    print(f"\n✅ S3 data lake verified and ready!")

verify_s3_contents(s3_client, BUCKET_NAME)

=== Contents of s3://fintech-analytics-2026/ ===

   processed/.keep                                                   0.0 KB
   processed/events_flat.parquet                                  2551.6 KB
   raw/.keep                                                         0.0 KB
   raw/year=2024/month=01/day=01/events.parquet                     31.6 KB
   raw/year=2024/month=01/day=02/events.parquet                     30.2 KB
   raw/year=2024/month=01/day=03/events.parquet                     36.1 KB
   raw/year=2024/month=01/day=04/events.parquet                     39.6 KB
   raw/year=2024/month=01/day=05/events.parquet                     48.9 KB
   raw/year=2024/month=01/day=06/events.parquet                     30.3 KB
   raw/year=2024/month=01/day=07/events.parquet                     25.5 KB
   raw/year=2024/month=01/day=08/events.parquet                     42.4 KB
   raw/year=2024/month=01/day=09/events.parquet                     38.8 KB
   raw/year=2024/month=01/day=10/events.parquet                     38.7 KB
   raw/year=2024/month=01/day=11/events.parquet                     37.5 KB
   raw/year=2024/month=01/day=12/events.parquet                     49.2 KB
   raw/year=2024/month=01/day=13/events.parquet                     31.2 KB
   raw/year=2024/month=01/day=14/events.parquet                     25.2 KB
   raw/year=2024/month=01/day=15/events.parquet                     32.4 KB
   raw/year=2024/month=01/day=16/events.parquet                     33.5 KB
   raw/year=2024/month=01/day=17/events.parquet                     38.3 KB
   raw/year=2024/month=01/day=18/events.parquet                     38.9 KB
   raw/year=2024/month=01/day=19/events.parquet                     47.7 KB
   raw/year=2024/month=01/day=20/events.parquet                     29.1 KB
   raw/year=2024/month=01/day=21/events.parquet                     26.3 KB
   raw/year=2024/month=01/day=22/events.parquet                     35.9 KB
   raw/year=2024/month=01/day=23/events.parquet                     34.1 KB
   raw/year=2024/month=01/day=24/events.parquet                     36.6 KB
   raw/year=2024/month=01/day=25/events.parquet                     41.1 KB
   raw/year=2024/month=01/day=26/events.parquet                     45.3 KB
   raw/year=2024/month=01/day=27/events.parquet                     29.4 KB
   raw/year=2024/month=01/day=28/events.parquet                     24.5 KB
   raw/year=2024/month=01/day=29/events.parquet                     33.8 KB
   raw/year=2024/month=01/day=30/events.parquet                     31.9 KB
   raw/year=2024/month=01/day=31/events.parquet                     32.7 KB
   raw/year=2024/month=02/day=01/events.parquet                     37.5 KB
   raw/year=2024/month=02/day=02/events.parquet                     45.5 KB
   raw/year=2024/month=02/day=03/events.parquet                     30.6 KB
   raw/year=2024/month=02/day=04/events.parquet                     26.3 KB
   raw/year=2024/month=02/day=05/events.parquet                     37.4 KB
   raw/year=2024/month=02/day=06/events.parquet                     34.5 KB
   raw/year=2024/month=02/day=07/events.parquet                     36.4 KB
   raw/year=2024/month=02/day=08/events.parquet                     34.8 KB
   raw/year=2024/month=02/day=09/events.parquet                     43.3 KB
   raw/year=2024/month=02/day=10/events.parquet                     30.9 KB
   raw/year=2024/month=02/day=11/events.parquet                     23.2 KB
   raw/year=2024/month=02/day=12/events.parquet                     36.4 KB
   raw/year=2024/month=02/day=13/events.parquet                     32.6 KB
   raw/year=2024/month=02/day=14/events.parquet                     42.1 KB
   raw/year=2024/month=02/day=15/events.parquet                     40.3 KB
   raw/year=2024/month=02/day=16/events.parquet                     45.9 KB
   raw/year=2024/month=02/day=17/events.parquet                     31.1 KB
   raw/year=2024/month=02/day=18/events.parquet                     29.7 KB
   raw/year=2024/month=02/day=19/events.parquet                     34.1 KB
   raw/year=2024/month=02/day=20/events.parquet                     31.7 KB
   raw/year=2024/month=02/day=21/events.parquet                     35.2 KB
   raw/year=2024/month=02/day=22/events.parquet                     44.6 KB
   raw/year=2024/month=02/day=23/events.parquet                     36.2 KB
   raw/year=2024/month=02/day=24/events.parquet                     34.5 KB
   raw/year=2024/month=02/day=25/events.parquet                     24.5 KB
   raw/year=2024/month=02/day=26/events.parquet                     31.2 KB
   raw/year=2024/month=02/day=27/events.parquet                     34.0 KB
   raw/year=2024/month=02/day=28/events.parquet                     34.3 KB
   raw/year=2024/month=02/day=29/events.parquet                     37.0 KB
   raw/year=2024/month=03/day=01/events.parquet                     47.4 KB
   raw/year=2024/month=03/day=02/events.parquet                     36.9 KB
   raw/year=2024/month=03/day=03/events.parquet                     28.9 KB
   raw/year=2024/month=03/day=04/events.parquet                     36.6 KB
   raw/year=2024/month=03/day=05/events.parquet                     34.4 KB
   raw/year=2024/month=03/day=06/events.parquet                     39.5 KB
   raw/year=2024/month=03/day=07/events.parquet                     43.9 KB
   raw/year=2024/month=03/day=08/events.parquet                     43.1 KB
   raw/year=2024/month=03/day=09/events.parquet                     26.3 KB
   raw/year=2024/month=03/day=10/events.parquet                     23.9 KB
   raw/year=2024/month=03/day=11/events.parquet                     38.3 KB
   raw/year=2024/month=03/day=12/events.parquet                     34.5 KB
   raw/year=2024/month=03/day=13/events.parquet                     37.9 KB
   raw/year=2024/month=03/day=14/events.parquet                     40.9 KB
   raw/year=2024/month=03/day=15/events.parquet                     45.9 KB
   raw/year=2024/month=03/day=16/events.parquet                     30.8 KB
   raw/year=2024/month=03/day=17/events.parquet                     25.9 KB
   raw/year=2024/month=03/day=18/events.parquet                     32.0 KB
   raw/year=2024/month=03/day=19/events.parquet                     30.2 KB
   raw/year=2024/month=03/day=20/events.parquet                     36.8 KB
   raw/year=2024/month=03/day=21/events.parquet                     38.6 KB
   raw/year=2024/month=03/day=22/events.parquet                     41.8 KB
   raw/year=2024/month=03/day=23/events.parquet                     31.4 KB
   raw/year=2024/month=03/day=24/events.parquet                     27.4 KB
   raw/year=2024/month=03/day=25/events.parquet                     32.5 KB
   raw/year=2024/month=03/day=26/events.parquet                     33.1 KB
   raw/year=2024/month=03/day=27/events.parquet                     40.7 KB
   raw/year=2024/month=03/day=28/events.parquet                     40.4 KB
   raw/year=2024/month=03/day=29/events.parquet                     38.8 KB
   raw/year=2024/month=03/day=30/events.parquet                     26.7 KB
   reports/.keep                                                     0.0 KB

──────────────────────────────────────────────────────────────────────
   Total files : 94
   Total size  : 5729.3 KB

✅ S3 data lake verified and ready!

In [8]:
import duckdb

def download_and_query_s3(s3, bucket: str):
    local_download = "data/processed/events_from_s3.parquet"
    s3_key         = "processed/events_flat.parquet"

    print("Step 1: Downloading from S3...")
    s3.download_file(bucket, s3_key, local_download)
    print(f"   ✅ Downloaded → {local_download}")

    print("\nStep 2: Querying with DuckDB...")
    con = duckdb.connect()

    summary = con.execute(f"""
        SELECT
            user_segment,
            COUNT(DISTINCT user_id)    AS unique_users,
            COUNT(*)                   AS total_events,
            COUNT(DISTINCT session_id) AS total_sessions,
            ROUND(SUM(amount), 2)      AS total_revenue_naira
        FROM read_parquet('{local_download}')
        GROUP BY user_segment
        ORDER BY total_events DESC
    """).fetchdf()

    print("\n=== Data pulled from S3 → queried with DuckDB ===")
    print(summary.to_string(index=False))
    print(f"\n✅ Full pipeline confirmed:")
    print(f"   Python → Parquet → S3 → DuckDB ✓")

download_and_query_s3(s3_client, BUCKET_NAME)

Step 1: Downloading from S3...
   ✅ Downloaded → data/processed/events_from_s3.parquet

Step 2: Querying with DuckDB...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

=== Data pulled from S3 → queried with DuckDB ===
user_segment  unique_users  total_events  total_sessions  total_revenue_naira
       power            67         33881            5840         723493699.35
     regular           124         12043            2500         204343158.75
      lurker           381          4076             953          52438197.26

✅ Full pipeline confirmed:
   Python → Parquet → S3 → DuckDB ✓

In [9]:
!git add .
!git commit -m "Day 5: AWS S3 data lake — uploads complete"
!git push origin main

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

Everything up-to-date

In [10]:
# Run this cell to understand the pipeline before building it

pipeline_overview = """
╔══════════════════════════════════════════════════════════════╗
║              DAILY ANALYTICS PIPELINE                        ║
║                                                              ║
║  What this pipeline does every day:                          ║
║                                                              ║
║  STEP 1: Extract                                             ║
║  → Read raw event parquet files from AWS S3                  ║
║  → Load into DuckDB for fast processing                      ║
║                                                              ║
║  STEP 2: Transform                                           ║
║  → Calculate DAU (Daily Active Users)                        ║
║  → Calculate MAU (Monthly Active Users)                      ║
║  → Calculate Revenue per user segment                        ║
║  → Calculate Engagement Score per user                       ║
║  → Classify users into lifecycle stages                      ║
║     (New → Active → At-Risk → Churned)                       ║
║                                                              ║
║  STEP 3: Load                                                ║
║  → Save daily summary back to S3                             ║
║  → Save user metrics table to S3                             ║
║                                                              ║
║  STEP 4: Validate                                            ║
║  → Check data quality                                        ║
║  → Flag any anomalies                                        ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝
"""
print(pipeline_overview)

╔══════════════════════════════════════════════════════════════╗
║              DAILY ANALYTICS PIPELINE                        ║
║                                                              ║
║  What this pipeline does every day:                          ║
║                                                              ║
║  STEP 1: Extract                                             ║
║  → Read raw event parquet files from AWS S3                  ║
║  → Load into DuckDB for fast processing                      ║
║                                                              ║
║  STEP 2: Transform                                           ║
║  → Calculate DAU (Daily Active Users)                        ║
║  → Calculate MAU (Monthly Active Users)                      ║
║  → Calculate Revenue per user segment                        ║
║  → Calculate Engagement Score per user                       ║
║  → Classify users into lifecycle stages                      ║
║     (New → Active → At-Risk → Churned)                       ║
║                                                              ║
║  STEP 3: Load                                                ║
║  → Save daily summary back to S3                             ║
║  → Save user metrics table to S3                             ║
║                                                              ║
║  STEP 4: Validate                                            ║
║  → Check data quality                                        ║
║  → Flag any anomalies                                        ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝

In [12]:
import pandas as pd
import numpy as np
import duckdb
import boto3
import os
import json
from datetime import datetime, timedelta
from dotenv import load_dotenv, find_dotenv  # ← find_dotenv added here

# Reload credentials
load_dotenv(find_dotenv(), override=True)

AWS_ACCESS_KEY = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
BUCKET_NAME    = os.getenv("AWS_BUCKET_NAME")
AWS_REGION     = os.getenv("AWS_REGION")

# Create S3 client
s3 = boto3.client(
    "s3",
    aws_access_key_id     = AWS_ACCESS_KEY,
    aws_secret_access_key = AWS_SECRET_KEY,
    region_name           = AWS_REGION
)

# Create DuckDB connection
con = duckdb.connect()

print("✅ All imports loaded!")
print(f"   Bucket : {BUCKET_NAME}")
print(f"   Region : {AWS_REGION}")

✅ All imports loaded!
   Bucket : fintech-analytics-2026
   Region : eu-north-1

In [13]:
def extract_raw_events():
    """
    STEP 1 — EXTRACT
    Read the raw event data from local parquet files into DuckDB.
    In a real Airflow pipeline this would pull directly from S3.
    We use local files for speed and reliability in the notebook.
    """
    print("=" * 55)
    print("STEP 1: EXTRACT — Loading raw events")
    print("=" * 55)

    # DuckDB reads ALL partitions at once with ** wildcard
    # This is one of DuckDB's most powerful features
    raw_data = con.execute("""
        SELECT
            event_id,
            user_id,
            event_type,
            timestamp,
            amount,
            session_id,
            device_type,
            location_city,
            user_tenure_days,
            user_segment,
            DATE(timestamp)                    AS event_date,
            EXTRACT(HOUR FROM timestamp)       AS event_hour,
            EXTRACT(DOW  FROM timestamp)       AS day_of_week,
            EXTRACT(MONTH FROM timestamp)      AS event_month
        FROM read_parquet('data/raw/**/*.parquet')
        ORDER BY timestamp
    """).fetchdf()

    print(f"✅ Extracted {len(raw_data):,} raw events")
    print(f"   Date range    : {raw_data['event_date'].min()} → {raw_data['event_date'].max()}")
    print(f"   Unique users  : {raw_data['user_id'].nunique():,}")
    print(f"   Unique sessions: {raw_data['session_id'].nunique():,}")
    print(f"   Columns       : {list(raw_data.columns)}")

    return raw_data

# Run Step 1
raw_df = extract_raw_events()
raw_df.head(3)

=======================================================
STEP 1: EXTRACT — Loading raw events
=======================================================
✅ Extracted 50,000 raw events
   Date range    : 2024-01-01 00:00:00 → 2024-03-30 00:00:00
   Unique users  : 572
   Unique sessions: 9,293
   Columns       : ['event_id', 'user_id', 'event_type', 'timestamp', 'amount', 'session_id', 'device_type', 'location_city', 'user_tenure_days', 'user_segment', 'event_date', 'event_hour', 'day_of_week', 'event_month']

,event_id,user_id,event_type,timestamp,amount,session_id,device_type,location_city,user_tenure_days,user_segment,event_date,event_hour,day_of_week,event_month
0,18c84fed-8cee-4d7b-a95c-9b94886be45b,USR00339,app_open,2024-01-01 05:40:58,NaN,111b2375,android,Port Harcourt,190,power,2024-01-01,5,1,1
1,7161298c-8bf2-4a25-9160-9834a12183c5,USR00339,login,2024-01-01 05:41:04,NaN,111b2375,android,Port Harcourt,190,power,2024-01-01,5,1,1
2,e40835c3-d03a-4bae-aabf-e34e00bf1e6a,USR00339,deposit_money,2024-01-01 05:41:08,231685.7,111b2375,android,Port Harcourt,190,power,2024-01-01,5,1,1

In [14]:
def calculate_dau_mau(raw_df: pd.DataFrame):
    """
    DAU = Daily Active Users
    MAU = Monthly Active Users

    DAU/MAU ratio is one of the most important health metrics
    for any app. A ratio above 20% means good engagement.
    PiggyVest/Cowrywise would track this every single day.
    """
    print("=" * 55)
    print("STEP 2a: TRANSFORM — Calculating DAU and MAU")
    print("=" * 55)

    # Register dataframe in DuckDB so we can query it with SQL
    con.register("events", raw_df)

    # DAU — count unique users per day
    dau = con.execute("""
        SELECT
            event_date                      AS date,
            COUNT(DISTINCT user_id)         AS daily_active_users,
            COUNT(DISTINCT session_id)      AS daily_sessions,
            COUNT(*)                        AS daily_events,
            ROUND(COUNT(*) * 1.0 /
                COUNT(DISTINCT user_id), 2) AS events_per_user
        FROM events
        GROUP BY event_date
        ORDER BY event_date
    """).fetchdf()

    # MAU — count unique users per month
    mau = con.execute("""
        SELECT
            event_month                     AS month,
            COUNT(DISTINCT user_id)         AS monthly_active_users
        FROM events
        GROUP BY event_month
        ORDER BY event_month
    """).fetchdf()

    # DAU/MAU ratio — merge and calculate
    dau["month"] = pd.to_datetime(dau["date"]).dt.month
    dau = dau.merge(mau, on="month", how="left")
    dau["dau_mau_ratio"] = (
        dau["daily_active_users"] / dau["monthly_active_users"]
    ).round(4)

    print(f"✅ DAU/MAU calculated for {len(dau)} days")
    print(f"\n   Average DAU        : {dau['daily_active_users'].mean():.0f} users/day")
    print(f"   Average MAU        : {dau['monthly_active_users'].mean():.0f} users/month")
    print(f"   Average DAU/MAU    : {dau['dau_mau_ratio'].mean():.1%}")
    print(f"\n   (A DAU/MAU above 20% = healthy engagement)")

    return dau, mau

# Run Step 2a
dau_df, mau_df = calculate_dau_mau(raw_df)
print(f"\nSample DAU data (first 5 days):")
dau_df[["date", "daily_active_users", "daily_sessions", "dau_mau_ratio"]].head()

=======================================================
STEP 2a: TRANSFORM — Calculating DAU and MAU
=======================================================
✅ DAU/MAU calculated for 90 days

   Average DAU        : 75 users/day
   Average MAU        : 418 users/month
   Average DAU/MAU    : 18.0%

   (A DAU/MAU above 20% = healthy engagement)

Sample DAU data (first 5 days):

        date  daily_active_users  daily_sessions  dau_mau_ratio
0 2024-01-01                  72              92         0.1667
1 2024-01-02                  66              84         0.1528
2 2024-01-03                  79             106         0.1829
3 2024-01-04                  88             121         0.2037
4 2024-01-05                 100             151         0.2315

In [15]:
def calculate_engagement_scores(raw_df: pd.DataFrame):
    """
    Engagement Score = (logins × 0.3) + (transactions × 0.7)

    This formula values financial actions (deposits, withdrawals)
    more than passive actions (logins, views).
    A user who logs in every day but never transacts is
    less valuable than one who transacts weekly.
    """
    print("=" * 55)
    print("STEP 2b: TRANSFORM — Calculating Engagement Scores")
    print("=" * 55)

    con.register("events", raw_df)

    engagement = con.execute("""
        SELECT
            user_id,
            user_segment,
            location_city,
            device_type,
            user_tenure_days,

            -- Count each action type per user
            COUNT(*)                                        AS total_events,
            COUNT(DISTINCT session_id)                      AS total_sessions,
            COUNT(DISTINCT event_date)                      AS active_days,

            SUM(CASE WHEN event_type = 'login'
                THEN 1 ELSE 0 END)                          AS total_logins,

            SUM(CASE WHEN event_type IN
                ('deposit_money', 'withdraw_money',
                 'create_savings_plan')
                THEN 1 ELSE 0 END)                          AS total_transactions,

            ROUND(SUM(CASE WHEN amount IS NOT NULL
                THEN amount ELSE 0 END), 2)                 AS total_amount_naira,

            -- Engagement Score formula
            ROUND(
                (SUM(CASE WHEN event_type = 'login'
                    THEN 1 ELSE 0 END) * 0.3) +
                (SUM(CASE WHEN event_type IN
                    ('deposit_money', 'withdraw_money',
                     'create_savings_plan')
                    THEN 1 ELSE 0 END) * 0.7),
            2)                                              AS engagement_score,

            -- Last active date
            MAX(event_date)                                 AS last_active_date,

            -- First active date
            MIN(event_date)                                 AS first_active_date

        FROM events
        GROUP BY
            user_id, user_segment, location_city,
            device_type, user_tenure_days
        ORDER BY engagement_score DESC
    """).fetchdf()

    print(f"✅ Engagement scores calculated for {len(engagement):,} users")
    print(f"\n   Score breakdown:")
    print(f"   Highest score : {engagement['engagement_score'].max():.1f}")
    print(f"   Average score : {engagement['engagement_score'].mean():.1f}")
    print(f"   Lowest score  : {engagement['engagement_score'].min():.1f}")
    print(f"\n   Top 5 most engaged users:")
    print(engagement[["user_id", "user_segment",
                       "engagement_score", "total_transactions",
                       "total_amount_naira"]].head().to_string(index=False))

    return engagement

# Run Step 2b
engagement_df = calculate_engagement_scores(raw_df)
engagement_df.head(3)

=======================================================
STEP 2b: TRANSFORM — Calculating Engagement Scores
=======================================================
✅ Engagement scores calculated for 572 users

   Score breakdown:
   Highest score : 142.3
   Average score : 15.2
   Lowest score  : 0.3

   Top 5 most engaged users:
 user_id user_segment  engagement_score  total_transactions  total_amount_naira
USR00441        power             142.3               148.0         15823990.12
USR00080        power             141.0               147.0         19903478.25
USR00008        power             133.7               140.0         16372237.64
USR00049        power             133.7               140.0         14965452.00
USR00325        power             130.4               131.0         16590083.35

,user_id,user_segment,location_city,device_type,user_tenure_days,total_events,total_sessions,active_days,total_logins,total_transactions,total_amount_naira,engagement_score,last_active_date,first_active_date
0,USR00441,power,Benin City,android,327,750,129,62,129.0,148.0,15823990.12,142.3,2024-03-30,2024-01-01
1,USR00080,power,Benin City,web,273,742,127,72,127.0,147.0,19903478.25,141.0,2024-03-29,2024-01-02
2,USR00008,power,Port Harcourt,ios,22,704,119,71,119.0,140.0,16372237.64,133.7,2024-03-28,2024-01-01

In [16]:
def classify_user_lifecycle(engagement_df: pd.DataFrame):
    """
    Classify every user into a lifecycle stage based on
    how recently they were active:

    New      → joined in last 7 days
    Active   → used app in last 7 days
    At-Risk  → last active 8–30 days ago
    Churned  → not active for 30+ days

    This is one of the most valuable outputs for the
    business — it tells them exactly who to target
    with re-engagement campaigns.
    """
    print("=" * 55)
    print("STEP 2c: TRANSFORM — Classifying User Lifecycle")
    print("=" * 55)

    # Reference date = last day in our dataset
    reference_date = pd.to_datetime("2024-03-31")

    df = engagement_df.copy()
    df["last_active_date"]  = pd.to_datetime(df["last_active_date"])
    df["first_active_date"] = pd.to_datetime(df["first_active_date"])
    df["days_since_active"] = (
        reference_date - df["last_active_date"]
    ).dt.days

    # Classify lifecycle stage
    def assign_stage(row):
        if row["days_since_active"] <= 7:
            if row["first_active_date"] >= reference_date - timedelta(days=7):
                return "New"
            return "Active"
        elif row["days_since_active"] <= 30:
            return "At-Risk"
        else:
            return "Churned"

    df["lifecycle_stage"] = df.apply(assign_stage, axis=1)

    # Summary
    stage_summary = df["lifecycle_stage"].value_counts()

    print(f"✅ Lifecycle classification complete!")
    print(f"\n   Stage breakdown:")
    for stage, count in stage_summary.items():
        pct = count / len(df) * 100
        bar = "█" * int(pct / 2)
        print(f"   {stage:<10} : {count:>4} users ({pct:.1f}%) {bar}")

    # Business insight
    at_risk = stage_summary.get("At-Risk", 0)
    churned = stage_summary.get("Churned", 0)
    print(f"\n   ⚠️  {at_risk} users are At-Risk of churning")
    print(f"   ❌  {churned} users have already Churned")
    print(f"   💡  Launch re-engagement campaign for At-Risk users!")

    return df

# Run Step 2c
lifecycle_df = classify_user_lifecycle(engagement_df)
lifecycle_df[["user_id", "user_segment",
              "days_since_active", "lifecycle_stage",
              "engagement_score"]].head(10)

=======================================================
STEP 2c: TRANSFORM — Classifying User Lifecycle
=======================================================
✅ Lifecycle classification complete!

   Stage breakdown:
   Active     :  223 users (39.0%) ███████████████████
   At-Risk    :  195 users (34.1%) █████████████████
   Churned    :  148 users (25.9%) ████████████
   New        :    6 users (1.0%)

   ⚠️  195 users are At-Risk of churning
   ❌  148 users have already Churned
   💡  Launch re-engagement campaign for At-Risk users!

    user_id user_segment  days_since_active lifecycle_stage  engagement_score
0  USR00441        power                  1          Active             142.3
1  USR00080        power                  2          Active             141.0
2  USR00008        power                  3          Active             133.7
3  USR00049        power                  2          Active             133.7
4  USR00325        power                  1          Active             130.4
5  USR00500        power                  2          Active             130.2
6  USR00102        power                  1          Active             130.1
7  USR00351        power                  1          Active             127.7
8  USR00152        power                  1          Active             125.7
9  USR00306        power                  1          Active             124.9

In [17]:
def calculate_revenue_metrics(raw_df: pd.DataFrame):
    """
    Calculate revenue metrics broken down by:
    - User segment (power, regular, lurker)
    - City
    - Device type
    - Month
    """
    print("=" * 55)
    print("STEP 2d: TRANSFORM — Revenue Metrics")
    print("=" * 55)

    con.register("events", raw_df)

    # Revenue by segment
    revenue_segment = con.execute("""
        SELECT
            user_segment,
            COUNT(DISTINCT user_id)             AS users,
            COUNT(*)                            AS transactions,
            ROUND(SUM(amount), 2)               AS total_revenue,
            ROUND(AVG(amount), 2)               AS avg_transaction,
            ROUND(SUM(amount) /
                COUNT(DISTINCT user_id), 2)     AS revenue_per_user
        FROM events
        WHERE amount IS NOT NULL
        GROUP BY user_segment
        ORDER BY total_revenue DESC
    """).fetchdf()

    # Revenue by city
    revenue_city = con.execute("""
        SELECT
            location_city,
            COUNT(DISTINCT user_id)             AS users,
            ROUND(SUM(amount), 2)               AS total_revenue,
            ROUND(AVG(amount), 2)               AS avg_transaction
        FROM events
        WHERE amount IS NOT NULL
        GROUP BY location_city
        ORDER BY total_revenue DESC
    """).fetchdf()

    # Revenue by month
    revenue_month = con.execute("""
        SELECT
            event_month                         AS month,
            COUNT(DISTINCT user_id)             AS active_users,
            ROUND(SUM(amount), 2)               AS total_revenue,
            ROUND(AVG(amount), 2)               AS avg_transaction
        FROM events
        WHERE amount IS NOT NULL
        GROUP BY event_month
        ORDER BY event_month
    """).fetchdf()

    print("✅ Revenue metrics calculated!\n")

    print("   Revenue by Segment:")
    print(revenue_segment.to_string(index=False))

    print("\n   Revenue by City:")
    print(revenue_city.to_string(index=False))

    print("\n   Revenue by Month:")
    print(revenue_month.to_string(index=False))

    return revenue_segment, revenue_city, revenue_month

# Run Step 2d
rev_segment, rev_city, rev_month = calculate_revenue_metrics(raw_df)

=======================================================
STEP 2d: TRANSFORM — Revenue Metrics
=======================================================
✅ Revenue metrics calculated!

   Revenue by Segment:
user_segment  users  transactions  total_revenue  avg_transaction  revenue_per_user
       power     67          3564   723493699.35        203000.48       10798413.42
     regular    123          1002   204343158.75        203935.29        1661326.49
      lurker    201           281    52438197.26        186612.80         260886.55

   Revenue by City:
location_city  users  total_revenue  avg_transaction
        Abuja     56   162810783.03        201998.49
   Benin City     66   157521657.83        205910.66
       Ibadan     64   128995864.79        204755.34
Port Harcourt     45   123807881.30        198092.61
        Lagos     45   120856504.53        199104.62
         Kano     39   120833443.04        199066.63
        Enugu     35    88006847.73        197324.77
       Kaduna     41    77442073.11        214520.98

   Revenue by Month:
 month  active_users  total_revenue  avg_transaction
     1           271   340327669.79        204523.84
     2           235   316006147.57        204534.72
     3           265   323941238.00        197766.32

In [18]:
def load_results_to_s3(dau_df, lifecycle_df,
                        rev_segment, rev_city, rev_month):
    """
    STEP 3 — LOAD
    Save all processed results back to S3 and locally.
    These files are what Power BI will connect to.
    """
    print("=" * 55)
    print("STEP 3: LOAD — Saving Results")
    print("=" * 55)

    os.makedirs("data/processed", exist_ok=True)

    # Files to save
    files_to_save = {
        "data/processed/dau_metrics.parquet"      : dau_df,
        "data/processed/user_lifecycle.parquet"   : lifecycle_df,
        "data/processed/revenue_by_segment.parquet": rev_segment,
        "data/processed/revenue_by_city.parquet"  : rev_city,
        "data/processed/revenue_by_month.parquet" : rev_month,
    }

    saved_files = []

    for local_path, df in files_to_save.items():
        # Save locally
        df.to_parquet(local_path, index=False)
        size_kb = os.path.getsize(local_path) / 1024

        # Upload to S3
        s3_key = local_path.replace("data/", "")
        s3.upload_file(local_path, BUCKET_NAME, s3_key)

        print(f"   ✅ {local_path:<45} {size_kb:>6.1f} KB → S3")
        saved_files.append(local_path)

    print(f"\n✅ All {len(saved_files)} files saved locally and uploaded to S3!")
    print(f"\n   These files are ready for Power BI:")
    for f in saved_files:
        print(f"   → {f}")

    return saved_files

# Run Step 3
saved = load_results_to_s3(
    dau_df, lifecycle_df,
    rev_segment, rev_city, rev_month
)

=======================================================
STEP 3: LOAD — Saving Results
=======================================================
   ✅ data/processed/dau_metrics.parquet               8.1 KB → S3
   ✅ data/processed/user_lifecycle.parquet           25.8 KB → S3
   ✅ data/processed/revenue_by_segment.parquet        4.2 KB → S3
   ✅ data/processed/revenue_by_city.parquet           3.2 KB → S3
   ✅ data/processed/revenue_by_month.parquet          3.0 KB → S3

✅ All 5 files saved locally and uploaded to S3!

   These files are ready for Power BI:
   → data/processed/dau_metrics.parquet
   → data/processed/user_lifecycle.parquet
   → data/processed/revenue_by_segment.parquet
   → data/processed/revenue_by_city.parquet
   → data/processed/revenue_by_month.parquet

In [19]:
def validate_pipeline_output():
    """
    STEP 4 — VALIDATE
    Check that everything looks correct.
    In production pipelines this step catches problems
    before bad data reaches the dashboard.
    """
    print("=" * 55)
    print("STEP 4: VALIDATE — Data Quality Checks")
    print("=" * 55)

    checks = []

    # Check 1: DAU file exists and has data
    dau_check = pd.read_parquet("data/processed/dau_metrics.parquet")
    check1 = len(dau_check) > 0
    checks.append(("DAU file has data", check1))

    # Check 2: No negative revenue
    rev_check = pd.read_parquet("data/processed/revenue_by_segment.parquet")
    check2 = (rev_check["total_revenue"] >= 0).all()
    checks.append(("No negative revenue", check2))

    # Check 3: All lifecycle stages are valid
    life_check  = pd.read_parquet("data/processed/user_lifecycle.parquet")
    valid_stages = {"New", "Active", "At-Risk", "Churned"}
    check3 = set(life_check["lifecycle_stage"].unique()).issubset(valid_stages)
    checks.append(("Valid lifecycle stages", check3))

    # Check 4: No duplicate users in lifecycle table
    check4 = life_check["user_id"].nunique() == len(life_check)
    checks.append(("No duplicate users", check4))

    # Check 5: DAU never exceeds total users
    check5 = dau_check["daily_active_users"].max() <= 1000
    checks.append(("DAU within expected range", check5))

    # Print results
    print("\n   Quality Check Results:")
    all_passed = True
    for check_name, passed in checks:
        status = "✅ PASS" if passed else "❌ FAIL"
        print(f"   {status} → {check_name}")
        if not passed:
            all_passed = False

    if all_passed:
        print(f"\n🎉 All {len(checks)} checks passed!")
        print("   Pipeline output is clean and ready.")
    else:
        print(f"\n⚠️  Some checks failed — review data before proceeding")

    return all_passed

# Run Step 4
pipeline_ok = validate_pipeline_output()

=======================================================
STEP 4: VALIDATE — Data Quality Checks
=======================================================

   Quality Check Results:
   ✅ PASS → DAU file has data
   ✅ PASS → No negative revenue
   ✅ PASS → Valid lifecycle stages
   ✅ PASS → No duplicate users
   ✅ PASS → DAU within expected range

🎉 All 5 checks passed!
   Pipeline output is clean and ready.

In [20]:
def run_full_pipeline():
    """
    This function runs all 4 pipeline steps in sequence.
    This is exactly what Airflow would trigger automatically
    every day at 2am in a production environment.
    """
    print("🚀 STARTING DAILY ANALYTICS PIPELINE")
    print(f"   Run time : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 55)

    start_time = datetime.now()

    # Step 1: Extract
    raw_df = extract_raw_events()
    print()

    # Step 2: Transform
    dau_df, mau_df              = calculate_dau_mau(raw_df)
    print()
    engagement_df               = calculate_engagement_scores(raw_df)
    print()
    lifecycle_df                = classify_user_lifecycle(engagement_df)
    print()
    rev_segment, rev_city, rev_month = calculate_revenue_metrics(raw_df)
    print()

    # Step 3: Load
    saved = load_results_to_s3(
        dau_df, lifecycle_df,
        rev_segment, rev_city, rev_month
    )
    print()

    # Step 4: Validate
    pipeline_ok = validate_pipeline_output()

    # Pipeline summary
    duration = (datetime.now() - start_time).seconds
    print(f"\n{'=' * 55}")
    print(f"✅ PIPELINE COMPLETE")
    print(f"   Duration  : {duration} seconds")
    print(f"   Status    : {'SUCCESS' if pipeline_ok else 'WARNING'}")
    print(f"   Files     : {len(saved)} files saved to S3")
    print(f"   Timestamp : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"{'=' * 55}")

    return {
        "raw_df"       : raw_df,
        "dau_df"       : dau_df,
        "lifecycle_df" : lifecycle_df,
        "rev_segment"  : rev_segment,
        "rev_city"     : rev_city,
        "rev_month"    : rev_month
    }

# ── Run the full pipeline ─────────────────────────────────────────────────
pipeline_results = run_full_pipeline()

🚀 STARTING DAILY ANALYTICS PIPELINE
   Run time : 2026-04-01 12:23:52
=======================================================
=======================================================
STEP 1: EXTRACT — Loading raw events
=======================================================
✅ Extracted 50,000 raw events
   Date range    : 2024-01-01 00:00:00 → 2024-03-30 00:00:00
   Unique users  : 572
   Unique sessions: 9,293
   Columns       : ['event_id', 'user_id', 'event_type', 'timestamp', 'amount', 'session_id', 'device_type', 'location_city', 'user_tenure_days', 'user_segment', 'event_date', 'event_hour', 'day_of_week', 'event_month']

=======================================================
STEP 2a: TRANSFORM — Calculating DAU and MAU
=======================================================
✅ DAU/MAU calculated for 90 days

   Average DAU        : 75 users/day
   Average MAU        : 418 users/month
   Average DAU/MAU    : 18.0%

   (A DAU/MAU above 20% = healthy engagement)

=======================================================
STEP 2b: TRANSFORM — Calculating Engagement Scores
=======================================================
✅ Engagement scores calculated for 572 users

   Score breakdown:
   Highest score : 142.3
   Average score : 15.2
   Lowest score  : 0.3

   Top 5 most engaged users:
 user_id user_segment  engagement_score  total_transactions  total_amount_naira
USR00441        power             142.3               148.0         15823990.12
USR00080        power             141.0               147.0         19903478.25
USR00049        power             133.7               140.0         14965452.00
USR00008        power             133.7               140.0         16372237.64
USR00325        power             130.4               131.0         16590083.35

=======================================================
STEP 2c: TRANSFORM — Classifying User Lifecycle
=======================================================
✅ Lifecycle classification complete!

   Stage breakdown:
   Active     :  223 users (39.0%) ███████████████████
   At-Risk    :  195 users (34.1%) █████████████████
   Churned    :  148 users (25.9%) ████████████
   New        :    6 users (1.0%)

   ⚠️  195 users are At-Risk of churning
   ❌  148 users have already Churned
   💡  Launch re-engagement campaign for At-Risk users!

=======================================================
STEP 2d: TRANSFORM — Revenue Metrics
=======================================================
✅ Revenue metrics calculated!

   Revenue by Segment:
user_segment  users  transactions  total_revenue  avg_transaction  revenue_per_user
       power     67          3564   723493699.35        203000.48       10798413.42
     regular    123          1002   204343158.75        203935.29        1661326.49
      lurker    201           281    52438197.26        186612.80         260886.55

   Revenue by City:
location_city  users  total_revenue  avg_transaction
        Abuja     56   162810783.03        201998.49
   Benin City     66   157521657.83        205910.66
       Ibadan     64   128995864.79        204755.34
Port Harcourt     45   123807881.30        198092.61
        Lagos     45   120856504.53        199104.62
         Kano     39   120833443.04        199066.63
        Enugu     35    88006847.73        197324.77
       Kaduna     41    77442073.11        214520.98

   Revenue by Month:
 month  active_users  total_revenue  avg_transaction
     1           271   340327669.79        204523.84
     2           235   316006147.57        204534.72
     3           265   323941238.00        197766.32

=======================================================
STEP 3: LOAD — Saving Results
=======================================================
   ✅ data/processed/dau_metrics.parquet               8.1 KB → S3
   ✅ data/processed/user_lifecycle.parquet           25.8 KB → S3
   ✅ data/processed/revenue_by_segment.parquet        4.2 KB → S3
   ✅ data/processed/revenue_by_city.parquet           3.2 KB → S3
   ✅ data/processed/revenue_by_month.parquet          3.0 KB → S3

✅ All 5 files saved locally and uploaded to S3!

   These files are ready for Power BI:
   → data/processed/dau_metrics.parquet
   → data/processed/user_lifecycle.parquet
   → data/processed/revenue_by_segment.parquet
   → data/processed/revenue_by_city.parquet
   → data/processed/revenue_by_month.parquet

=======================================================
STEP 4: VALIDATE — Data Quality Checks
=======================================================

   Quality Check Results:
   ✅ PASS → DAU file has data
   ✅ PASS → No negative revenue
   ✅ PASS → Valid lifecycle stages
   ✅ PASS → No duplicate users
   ✅ PASS → DAU within expected range

🎉 All 5 checks passed!
   Pipeline output is clean and ready.

=======================================================
✅ PIPELINE COMPLETE
   Duration  : 6 seconds
   Status    : SUCCESS
   Files     : 5 files saved to S3
   Timestamp : 2026-04-01 12:23:58
=======================================================

In [4]:
!git add .

In [6]:
!git commit -m "Day 6-7: Full analytics pipeline — DAU, engagement scores, lifecycle classification"

On branch main
nothing to commit, working tree clean

In [3]:
!git push origin main

fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

In [23]:
!git add .

In [24]:
!git commit -m "Add directory structure with .gitkeep placeholders"

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [25]:
!git push origin main

Everything up-to-date